[bot]
bot = true
token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
json_data_base = "XXX"

[servers]

    [servers.staf]
        id = "XXXXXXXXXXXXXXXXXX"
        cat = "XXXXXXXXXXXXXXXXXX"
        channels_bloque = "XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX"
        channel_creation = "XXXXXXXXXXXXXXXXXX"


